version: "3"
services:
  db:
    build:
      context: db/
    image: lewisemm/notes_api_db
    ports: 
      - "5432:5432"
  notes_api:
    build: .
    image: lewisemm/notes_api
    ports:
      - "8080:8080"
    environment:
      SETTINGS_MODULE: $SETTINGS_MODULE
      DATABASE_URL: $DATABASE_URL
    depends_on:
      - db
