# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-07 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170403_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
