# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-25 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180807_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
